### ISSUE TITLE
非SpringBoot环境使用报错

### ISSUE THREAD

**Issue by cdslily** [dromara/liteflow#10]
com.yomahub:liteflow-core:2.6.7 版本。
非Spring环境使用。

[INFO]2022-01-04 15:47:23.735 [main] com.yomahub.liteflow.core.FlowExecutor - flow info loaded from local file,path=config/flow.xml,format type=xml
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/util/Assert
        at com.yomahub.liteflow.parser.FlowParser.matchRuleResources(FlowParser.java:71)
        at com.yomahub.liteflow.parser.LocalXmlFlowParser.parseMain(LocalXmlFlowParser.java:25)
        at com.yomahub.liteflow.core.FlowExecutor.init(FlowExecutor.java:102)
        at cn.text.shop.jwest.TestFlowLite.main(TestFlowLite.java:17)
Caused by: java.lang.ClassNotFoundException: org.springframework.util.Assert
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

虽然引入org.springframework:spring-context:5.3.14 可以解决以上问题，但非Spring环境应能不依赖Spring framework相关组件。

**Comment by bryan31** [comment]
此问题在v2.6.11之后的版本已经支持
