### ISSUE TITLE
com.yomahub.liteflow.exception.WhenTimeoutException: Timed out when executing the component[t3]

### ISSUE THREAD

**Issue by cptjackwu** [dromara/liteflow#55]
2024-01-24 15:39:01.949 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-3] c.e.c.handle.iterator.MaterialGather     : =========工站号:OP10,物料采集,处理开始============
2024-01-24 15:39:01.949 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-4] c.eline.client.handle.iterator.PRGather  : =========工站号:OP10,工序控制和工位结果,处理开始============
2024-01-24 15:39:01.949 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-5] c.e.c.handle.iterator.QualityGather      : =========工站号:OP10,参数采集,处理开始============
2024-01-24 15:39:01.949 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-6] com.yomahub.liteflow.flow.element.Node   : [e74c627c265a418fbabb500c98daba34]:[O]start component[t4] execution
2024-01-24 15:39:01.950 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-6] c.e.client.handle.iterator.StockGather   : =========工站号:OP10,库存采集,处理开始============
2024-01-24 15:39:01.964 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-3] c.e.c.handle.iterator.MaterialGather     : =========工站号:OP10,采集精追数据:[]=======
2024-01-24 15:39:01.973 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-3] c.e.c.handle.iterator.MaterialGather     : =========工站号:OP10,采集物料数据:[RecordMaterialCollect(id=null, barcode=2400005, productCode=EH32, stationCode=OP10, stationName=OP10电机上线, orderCode=2131, materialBarcode=10000T0033440100000, materialCode=T0033440, materialName=电机壳体, workCard=null, shiftCode=SH001, createTime=Wed Jan 24 15:39:01 CST 2024)]=======
2024-01-24 15:39:01.974 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-3] c.e.c.handle.iterator.MaterialGather     : =========工站号:OP10,物料采集,处理结束============
2024-01-24 15:39:01.974 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-3] c.e.c.handle.iterator.MaterialGather     : [e74c627c265a418fbabb500c98daba34]:component[t1] finished in 24 milliseconds
2024-01-24 15:39:01.979 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-4] c.eline.client.handle.iterator.PRGather  : =========工站号:OP10,保存工序控制:RecordProcessControl(id=12, barcode=2400005, routeCode=EH32_routelist, currentStationCode=OP10, nextStationCodes=OP20,OP30, createTime=Wed Jan 24 15:39:01 CST 2024, updateTime=null)============
2024-01-24 15:39:01.989 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-5] c.e.c.handle.iterator.QualityGather      : [e74c627c265a418fbabb500c98daba34]:component[t3] finished in 39 milliseconds
2024-01-24 15:39:01.993 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-4] c.eline.client.handle.iterator.PRGather  : =========工站号:OP10,采集工位结果:RecordStationResult(id=43, barcode=2400005, productCode=EH32, modelCode=1, stationCode=OP10, stationName=OP10电机上线, worklineCode=DJ01, orderCode=2131, shiftCode=SH001, palletNumber=1, workCard=null, isRework=false, result=1, createTime=Wed Jan 24 15:39:01 CST 2024)============
2024-01-24 15:39:01.993 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-4] c.eline.client.handle.iterator.PRGather  : =========工站号:OP10,工序控制和工位结果,处理结束============
2024-01-24 15:39:01.993 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-4] c.eline.client.handle.iterator.PRGather  : [e74c627c265a418fbabb500c98daba34]:component[t2] finished in 44 milliseconds
2024-01-24 15:39:01.999 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-6] c.e.client.handle.iterator.StockGather   : =========工站号:OP10,库存采集,处理结束============
2024-01-24 15:39:01.999 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [      pool-13-thread-6] c.e.client.handle.iterator.StockGather   : [e74c627c265a418fbabb500c98daba34]:component[t4] finished in 49 milliseconds
2024-01-24 15:39:02.000 39046ad77a6e42849f96e4e83d4cad4c   WARN 53380 --- [68.8.81:20881-thread-1] c.y.l.f.p.s.AllOfParallelExecutor        : [e74c627c265a418fbabb500c98daba34]:executing thread has reached max-wait-seconds, thread canceled.Execute-item: [t3]
2024-01-24 15:39:02.000 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [68.8.81:20881-thread-1] c.y.l.f.p.s.AllOfParallelExecutor        : [e74c627c265a418fbabb500c98daba34]:when-executor[t3] execute failed. errorResume [false].
2024-01-24 15:39:02.002 39046ad77a6e42849f96e4e83d4cad4c  ERROR 53380 --- [68.8.81:20881-thread-1] c.y.l.f.e.condition.CatchCondition       : [e74c627c265a418fbabb500c98daba34]:catch exception:Timed out when executing the component[t3]

com.yomahub.liteflow.exception.WhenTimeoutException: Timed out when executing the component[t3]
	at com.yomahub.liteflow.flow.parallel.WhenFutureObj.timeOut(WhenFutureObj.java:45)
	at com.yomahub.liteflow.flow.parallel.strategy.ParallelStrategyExecutor.wrappedFutureObj(ParallelStrategyExecutor.java:55)
	at com.yomahub.liteflow.flow.parallel.strategy.ParallelStrategyExecutor.lambda$getWhenAllTaskList$2(ParallelStrategyExecutor.java:149)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.yomahub.liteflow.flow.parallel.strategy.ParallelStrategyExecutor.getWhenAllTaskList(ParallelStrategyExecutor.java:150)
	at com.yomahub.liteflow.flow.parallel.strategy.AllOfParallelExecutor.execute(AllOfParallelExecutor.java:21)
	at com.yomahub.liteflow.flow.element.condition.WhenCondition.executeAsyncCondition(WhenCondition.java:72)
	at com.yomahub.liteflow.flow.element.condition.WhenCondition.executeCondition(WhenCondition.java:56)
	at com.yomahub.liteflow.flow.element.Condition.execute(Condition.java:54)
	at com.yomahub.liteflow.flow.element.condition.ThenCondition.executeCondition(ThenCondition.java:44)
	at com.yomahub.liteflow.flow.element.Condition.execute(Condition.java:54)
	at com.yomahub.liteflow.flow.element.condition.CatchCondition.executeCondition(CatchCondition.java:35)
	at com.yomahub.liteflow.flow.element.Condition.execute(Condition.java:54)
	at com.yomahub.liteflow.flow.element.Chain.execute(Chain.java:92)
	at com.yomahub.liteflow.core.FlowExecutor.doExecute(FlowExecutor.java:403)
	at com.yomahub.liteflow.core.FlowExecutor.execute2Resp(FlowExecutor.java:323)
	at com.yomahub.liteflow.core.FlowExecutor.execute2Resp(FlowExecutor.java:269)
	at com.yomahub.liteflow.core.FlowExecutor.execute2Resp(FlowExecutor.java:264)
	at com.eline.client.handle.common.WorkComplete.handle(WorkComplete.java:27)
	at com.eline.client.handle.DefaultNodeHandler.lambda$handle$2(DefaultNodeHandler.java:61)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.eline.client.handle.DefaultNodeHandler.handle(DefaultNodeHandler.java:55)
	at org.apache.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java)
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84)
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at com.eline.client.filter.TraceIdFilter.invoke(TraceIdFilter.java:38)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:77)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:46)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:91)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:52)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:192)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:129)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:148)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.received(DubboProtocol.java:155)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:177)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.lang.Thread.run(Thread.java:748)

2024-01-24 15:39:02.005 39046ad77a6e42849f96e4e83d4cad4c   INFO 53380 --- [68.8.81:20881-thread-1] com.yomahub.liteflow.flow.element.Node   : [e74c627c265a418fbabb500c98daba34]:[O]start component[z] execution
2024-01-24 15:39:02.008 39046ad77a6e42849f96e4e83d4cad4c  ERROR 53380 --- [68.8.81:20881-thread-1] c.e.c.handle.common.ExceptionHandler     : ============工站号:OP10,服务异常=============

我用When执行的时间才1秒左右，他就报超时，问题出现在哪里

**Comment by fidoooooowang** [comment]
我遇到了同样的问题，请问你是怎么解决的？ @cptjackwu
